In [ ]:
#Name: Lillian Cunningham
#Class: 3474
#Section: 11am
#Assignment 1

In [ ]:
#Step 1.
with open("passwords.txt", "r") as file:
  a = [line.strip() for line in file]
print(a)

['bhall33,PASSWORD123', 'dcarter44,Admin', 'jrivera47,123456', 'khall11,qwerty', 'jmiller64,football', 'rrobinson21,password', 'jtaylor1,Master', 'lhall15,LETMEIN', 'elopez19,ABC123', 'kmoore51,baseball', 'nharris1,SHADOW', 'kallen70,Monkey', 'jlopez58,letmein', 'dhernandez84,Mustang', 'dsmith90,Password123', 'myoung83,LETMEIN', 'mscott56,123456', 'proberts27,Qwerty', 'tlee38,Mustang', 'kperez31,Batman', 'mramirez95,admin', 'elee55,Merlin', 'ethompson94,LetMeIn', 'ksmith40,Qwerty', 'jhill37,123456', 'cflores51,Football', 'rrivera42,ZXCVBNM', 'sthomas23,master', 'rwilliams88,Password123', 'kgarcia7,qwerty', 'mwilson2,Qwerty', 'lsanchez66,12345678', 'jrodriguez70,123456', 'dhill25,abc123', 'dperez51,123456', 'storres50,Thunder', 'jthompson4,ninja', 'bsmith97,abc123', 'jwhite29,ZXCVBNM', 'arobinson70,iloveyou', 'mjohnson40,QWERTY', 'dramirez94,monkey', 'pmartin61,letmein', 'bbaker23,123456', 'mdavis19,princess', 'dthomas29,hunter', 'dwilliams10,123456', 'lwright23,PASSWORD123', 'awright74,WELCOME', 'pramirez34,password123', 'sclark4,iloveyou', 'jgreen57,admin', 'abaker90,sunshine', 'nrivera50,TRUSTNO1', 'tmartinez23,LETMEIN', 'abrown3,123456', 'mwalker50,Thunder', 'aanderson11,hello', 'rbrown24,Welcome', 'lwalker36,123456', 'dgonzalez34,password123', 'adavis64,letmein', 'twilliams30,qwerty', 'tthomas41,password123', 'ayoung29,123456', 'pwright76,Password123', 'tgonzalez47,trustno1', 'lmartinez34,password123', 'mclark55,qwerty', 'arivera76,shadow', 'srivera7,thunder', 'tallen67,QWERTY', 'dhernandez4,QWERTY', 'jmartin9,111111', 'ajones73,ILoveYou', 'lnelson85,qwerty', 'sramirez6,password123', 'elewis34,superman', 'lwhite71,admin', 'khernandez57,Ginger', 'dcarter3,Football', 'jrivera56,admin', 'dmoore84,12345678', 'dperez45,123456', 'jmartin55,BATMAN', 'bjones35,password123', 'jnelson74,123456', 'tperez42,Hello', 'dsmith89,abc123', 'aperez44,letmein', 'staylor6,Ranger', 'jsmith74,football', 'ejones9,12345678', 'mwalker82,starwars', 'elee91,Sunshine', 'dramirez40,12345678', 'dbaker41,welcome', 'ttaylor14,admin', 'mmartinez17,123456', 'gadams74,letmein', 'cbaker53,password123', 'dthompson95,Dragon', 'jwalker14,master', 'dbaker70,TrustNo1', 'jrodriguez63,Abc123', 'wclark93,trustno1', 'rgreen3,monkey', 'lyoung11,Qwerty', 'cmoore98,password123', 'eadams91,mustang', 'rlewis32,hunter', 'danderson6,111111', 'gperez98,Monkey', 'charris44,PRINCESS', 'rking58,admin', 'sbrown72,Ninja', 'slee24,shadow', 'mmoore58,letmein', 'dmiller72,ILOVEYOU', 'tgarcia19,hunter', 'jwright74,123456', 'rrodriguez86,merlin', 'jlewis95,MONKEY', 'jking50,BASEBALL', 'gbrown75,Qwerty', 'kthompson8,QWERTY', 'pmitchell17,PASSWORD123', 'klee96,thunder', 'sjackson9,PASSWORD123', 'rmitchell31,Monkey', 'jjones24,123456', 'sbrown96,qwerty', 'lrodriguez56,letmein', 'rlopez89,password123', 'slee89,Master', 'tthompson37,PassWord123', 'kwilson22,PASSWORD', 'gtaylor82,password', 'ttorres60,Monkey', 'dscott17,123456', 'jjohnson70,password123', 'kdavis68,Password123', 'rgreen42,Diamond', 'nrodriguez20,merlin', 'mroberts16,PassWord123', 'tsanchez62,sunshine', 'chill35,123456', 'jlewis97,princess', 'eadams40,Password123', 'psmith58,123456', 'mthomas87,Sunshine', 'mjohnson14,iLoveYou', 'adavis35,PASSWORD', 'bmartinez47,letmein', 'nyoung28,iloveyou', 'mthompson54,Welcome', 'dwalker40,123456', 'bperez52,hello', 'twilliams24,Password', 'charris1,Password123', 'gking79,123456', 'aperez65,password', 'dking89,MONKEY', 'rmartin82,StarWars', 'rlee73,PASSWORD123', 'ptaylor89,qwerty', 'dharris42,admin', 'jthompson76,sunshine', 'snguyen32,qwerty', 'bclark96,batman', 'athompson23,Hello', 'bnelson38,PRINCESS', 'ladams47,Football', 'bhill86,master', 'ssmith79,trustno1', 'dmitchell8,HELLO', 'klee49,TRUSTNO1', 'sgonzalez4,ABC123', 'ssmith21,welcome', 'mlewis23,Batman', 'ryoung63,LetMeIn', 'mramirez71,PassWord123', 'mjackson84,Mustang', 'jlopez60,123456', 'jcarter52,hello', 'rnguyen53,DRAGON', 'mwhite32,123456', 'anguyen39,12345678', 'scampbell99,123456', 'dflores19,monkey', 'jjohnson18,trustno1', 'smiller35,dragon', 'sjackson18,Batman', 'jgarcia29,admin', 'mclark35,ZXCVBNM', 'myoung25,Password123', 'kwilliams90,Admin', 'thill32,123456', 'jwalker94,PASSWORD123', 'staylor8,123456', 'rking45,iloveyou', 'bking64,Admin', 'radams89,Admin', 'jperez40,Qwerty', 'cjohnson82,123456', 'aflores18,letmein', 'elee35,LetMeIn', 'eharris74,welcome', 'dwhite21,letmein', 'madams40,password123', 'sadams31,SUNSHINE', 'llewis64,PASSWORD123', 'emoore20,dragon', 'dwright77,123456', 'phernandez32,123456', 'dmoore54,QWERTY', 'jlopez22,welcome', 'cking63,Password', 'nscott93,LetMeIn', 'ewright48,TRUSTNO1', 'ebaker66,TrustNo1', 'rdavis31,NINJA', 'mjones61,Football', 'bcarter13,ABC123', 'jrodriguez64,qwerty', 'swilliams38,PASSWORD123', 'llewis20,ninja', 'rlee5,admin', 'gmartin82,princess', 'mtorres89,123456', 'cwilliams10,hello', 'ccarter58,123456', 'mtaylor6,password', 'dcampbell15,baseball', 'rwhite12,password', 'adavis2,letmein', 'mroberts35,ninja', 'btaylor97,baseball', 'bscott32,Hunter', 'bgarcia28,123456', 'gharris72,Password', 'rwhite63,trustno1', 'rscott69,Ninja', 'pramirez77,password123', 'bscott50,qwerty', 'athomas62,Welcome', 'tflores80,LETMEIN', 'rthomas51,Buster', 'klee3,Buster', 'rwilson24,123456', 'pcarter53,Mustang', 'eperez93,Qwerty', 'sharris79,Batman', 'jrodriguez84,Password', 'sscott73,Admin', 'kjones53,ABC123', 'gbrown11,football', 'lwilson10,qwerty', 'mcarter77,Batman', 'cscott96,password123', 'manderson11,Soccer', 'nwilson39,sunshine', 'jmartinez72,123456', 'rgonzalez3,baseball', 'srobinson50,Password123', 'rmartin66,soccer', 'sharris55,PassWord123', 'cflores94,qwerty', 'dwright68,password', 'arodriguez35,Password123', 'arivera78,QWERTY', 'mking52,iLoveYou', 'twright71,iloveyou', 'lclark95,Password123', 'tmiller8,ranger', 'cwright72,123456', 'eharris68,WELCOME', 'amartinez33,TRUSTNO1', 'amitchell51,qwerty', 'sramirez88,Master', 'pwilliams73,WELCOME', 'bthompson41,ILOVEYOU', 'scampbell97,Batman', 'mbaker38,iLoveYou', 'awhite7,admin', 'etaylor50,Baseball', 'arobinson3,Princess', 'dhernandez5,abc123', 'rnguyen56,ZXCVBNM', 'abrown19,admin', 'gsanchez12,superman', 'ngonzalez68,12345678', 'msanchez3,Dragon', 'tmitchell8,qwerty', 'awright43,admin', 'nmartin2,Football', 'djones71,Monkey', 'msanchez17,shadow', 'lwilliams48,welcome', 'anguyen79,sunshine', 'klopez19,Abc123', 'tmoore93,Welcome', 'kwhite72,admin', 'rmartin56,Batman', 'wflores86,LETMEIN', 'tbaker61,PASSWORD123', 'dflores72,12345678', 'mjackson98,Password123', 'sroberts58,ABC123', 'mbrown4,ABC123', 'mthompson4,123456', 'sscott71,Password123', 'jwalker40,Abc123', 'nallen1,ginger', 'gthompson60,12345678', 'sadams5,12345678', 'dmartinez10,MONKEY', 'sthomas19,dragon', 'jmiller16,123456', 'ssanchez83,Password123', 'gwilliams41,Dragon', 'mperez54,master', 'bbaker65,Admin', 'bmoore74,TRUSTNO1', 'madams25,TRUSTNO1', 'asanchez53,Qwerty', 'jnguyen4,qwerty', 'krobinson70,PASSWORD', 'mhall55,letmein', 'sramirez63,iLoveYou', 'ejackson8,sunshine', 'dnguyen12,MUSTANG', 'rtorres84,welcome', 'msanchez94,Master', 'mbrown95,123456', 'mhall61,Hello', 'ndavis31,123456', 'khill93,ADMIN', 'emiller51,qwerty', 'dbaker15,monkey', 'ethomas61,thunder', 'bhall34,123456', 'tclark96,Welcome', 'lrobinson23,letmein', 'mrobinson63,password123', 'aadams56,admin', 'cflores59,Password', 'rgonzalez22,123456', 'amartinez31,batman', 'dclark43,superman', 'jmartin97,QWERTY', 'abaker98,Sunshine', 'msmith42,password123', 'jflores81,LetMeIn', 'jrivera30,QWERTY', 'mrobinson59,Password123', 'gharris48,trustno1', 'lgonzalez96,admin', 'bcarter18,Shadow', 'tnelson49,LetMeIn', 'jrodriguez98,Baseball', 'ctorres67,PASSWORD', 'jramirez25,Password123', 'pmiller82,STARWARS', 'ebrown92,LETMEIN', 'sclark33,Shadow', 'jcarter85,123456', 'twilliams20,trustno1', 'jcampbell30,123456', 'cbrown65,123456', 'jjohnson36,Hunter', 'jcarter91,master', 'rhernandez49,Mustang', 'sgarcia74,QWERTY', 'jsmith24,password123', 'rhill90,123456', 'brodriguez35,WELCOME', 'bgarcia31,QWERTY', 'storres26,thunder', 'canderson4,dragon', 'knelson50,Admin', 'sflores31,password', 'sharris48,Welcome', 'chall79,123456', 'jgreen34,DRAGON', 'dnguyen13,Qwerty', 'ganderson71,welcome', 'swilliams1,123456', 'rjackson68,Qwerty', 'sscott98,Password123', 'rramirez66,123456', 'storres36,MONKEY', 'dsanchez26,Hunter', 'ddavis95,QWERTY', 'jmartinez9,TrustNo1', 'scarter61,Princess', 'cmitchell11,BASEBALL', 'pallen63,PASSWORD123', 'alopez34,MASTER', 'rgarcia36,Master', 'sjohnson66,football', 'thernandez78,123456', 'rcarter74,Dragon', 'rroberts70,QWERTY', 'awright3,qwerty', 'mmitchell46,Password123', 'cwalker79,StarWars', 'tmoore62,batman', 'mcampbell1,password123', 'dwright25,Password123', 'mbaker5,QWERTY', 'sadams54,111111', 'kmoore64,zxcvbnm', 'dharris54,qwerty', 'sjohnson91,Admin', 'jallen83,master', 'jhall35,Princess', 'emiller1,password123', 'aadams59,qwerty', 'ewilson29,123456', 'jmartin6,123456', 'mtaylor26,12345678', 'agreen66,password', 'kcarter75,BATMAN', 'sramirez69,111111', 'jrivera66,Password', 'storres75,admin', 'manderson4,Abc123', 'mroberts86,12345678', 'jadams66,Dragon', 'ehall8,Letmein', 'rtorres3,baseball', 'mflores90,Master', 'eramirez71,Password123', 'sdavis65,welcome', 'jsanchez29,Ranger', 'mlee30,Password', 'mdavis48,111111', 'ewilson45,shadow', 'ksmith16,QWERTY', 'jmiller36,PASSWORD123', 'aking94,Letmein', 'pharris47,ADMIN', 'jbrown25,STARWARS', 'lhill13,Welcome', 'kwalker1,iLoveYou', 'djohnson97,password123', 'mmoore17,12345678', 'shall64,DRAGON', 'dgarcia89,Princess', 'jtorres49,admin', 'rtorres58,LetMeIn', 'jwalker91,ninja', 'dgonzalez38,MUSTANG', 'bwhite89,MONKEY', 'tnelson44,TRUSTNO1', 'ljones93,Qwerty', 'wwhite24,Ginger', 'rlewis67,welcome', 'kwalker83,Abc123', 'rjohnson95,FOOTBALL', 'esanchez78,Password123', 'cking83,12345678', 'dtorres47,FOOTBALL', 'danderson14,Password123', 'khall26,ABC123', 'jflores46,QWERTY', 'pthomas79,LetMeIn', 'eclark92,admin', 'mperez25,master', 'mnguyen88,QWERTY', 'dperez30,STARWARS', 'shill64,BASEBALL', 'rthompson53,123456', 'jjones70,password', 'rbaker65,12345678', 'lclark29,Password123', 'ksmith80,Mustang', 'lflores65,password123', 'jramirez84,letmein', 'dgarcia79,qwerty', 'rwright38,SUPERMAN', 'sharris75,password', 'emartinez49,123456', 'ltorres2,password123', 'arobinson38,PASSWORD', 'rwright33,PASSWORD', 'arobinson88,123456', 'scarter28,MASTER', 'anelson38,BASEBALL', 'crodriguez78,Password', 'myoung8,PASSWORD123', 'crobinson38,password', 'tcampbell56,12345678', 'emartinez33,123456', 'ghall82,letmein', 'mhernandez18,Password', 'sscott34,Password123', 'jrodriguez14,111111', 'gjackson22,football', 'dlewis16,Mustang', 'rsmith60,sunshine', 'gtorres97,Password123', 'jhernandez30,Football', 'ewalker79,letmein', 'awalker42,superman', 'rclark89,ninja', 'jtorres43,princess', 'lcarter14,ABC123', 'jlopez9,qwerty', 'mflores27,Dragon', 'mperez7,qwerty', 'dthomas40,qwerty', 'tmiller59,Football', 'cperez77,admin', 'nrobinson32,12345678', 'snelson85,Princess', 'kmartinez72,Master', 'eking76,123456', 'sadams70,password123', 'jrivera4,ABC123', 'dperez33,WELCOME', 'mmartin38,iloveyou', 'asmith84,Football', 'rperez7,111111', 'gwhite72,thunder', 'tcampbell35,Batman', 'jgonzalez88,QWERTY', 'jcampbell93,StarWars', 'sbaker43,Dragon', 'emoore31,PASSWORD', 'srivera76,abc123', 'mallen45,thunder', 'tnelson65,admin', 'crodriguez4,qwerty', 'dthomas81,starwars', 'rmoore32,BASEBALL', 'jrivera10,123456', 'lrodriguez82,password123', 'bmartinez97,Admin', 'sscott63,Superman', 'jhall25,ILOVEYOU', 'cadams22,PASSWORD123', 'bgonzalez15,monkey', 'kdavis61,Hunter', 'jramirez37,123456', 'rdavis87,QWERTY', 'cbrown33,Welcome', 'sadams68,Monkey', 'dmitchell6,Princess', 'jhernandez55,master', 'mwhite11,Letmein', 'lflores61,MUSTANG', 'tramirez97,12345678', 'jlee6,MASTER', 'sperez38,letmein', 'cking96,letmein', 'kroberts75,admin', 'eadams28,password123', 'ghall11,ILoveYou', 'jyoung21,PassWord123', 'awilson16,letmein', 'lcampbell45,welcome', 'plewis85,WELCOME', 'dwhite99,PassWord123', 'rthompson19,welcome', 'jallen2,ABC123', 'egreen82,Princess', 'sallen57,QWERTY', 'gtorres26,ABC123', 'mcarter66,mustang', 'rhernandez55,letmein', 'bgreen2,password123', 'bnguyen85,qwerty', 'lmitchell28,baseball', 'enelson24,hello', 'lhall16,Welcome', 'rtorres79,master', 'dwilliams33,qwerty', 'mlewis98,Princess', 'dnelson79,TrustNo1', 'sjones67,LETMEIN', 'jthomas82,QWERTY', 'mgreen6,Dragon', 'sbrown34,Baseball', 'radams78,baseball', 'mwhite77,Password123', 'jnguyen12,111111', 'ldavis35,BASEBALL', 'clopez52,thunder', 'tmartin83,LetMeIn', 'manderson91,hello', 'jscott27,soccer', 'cmiller36,Letmein', 'sthomas29,Football', 'wwhite26,123456', 'bhill71,sunshine', 'djackson26,12345678', 'dnelson13,password123', 'ddavis23,Baseball', 'amitchell73,PASSWORD', 'jallen32,SHADOW', 'dbaker25,Baseball', 'wtaylor95,welcome', 'djackson17,password123', 'rwright51,123456', 'amartin66,Qwerty', 'jadams86,hello', 'kjones98,TrustNo1', 'sscott51,111111', 'cjones76,111111', 'ssmith51,LetMeIn', 'rjohnson72,TrustNo1', 'gwhite65,ABC123', 'jmiller35,Admin', 'mking56,welcome', 'jthomas63,dragon', 'aramirez96,Qwerty', 'cthompson92,sunshine', 'jscott31,123456', 'dking55,123456', 'awilson34,12345678', 'jgreen21,111111', 'mnelson78,TRUSTNO1', 'crodriguez63,letmein', 'edavis48,thunder', 'dharris33,Admin', 'jjohnson95,password123', 'tdavis8,Hunter', 'shill34,Baseball', 'kjohnson47,ninja', 'jyoung67,password123', 'jsmith42,MASTER', 'wroberts47,shadow', 'plewis80,111111', 'ejohnson98,MONKEY', 'pclark76,PASSWORD123', 'sthompson40,welcome', 'amartinez76,FOOTBALL', 'bmartin68,123456', 'banderson36,DRAGON', 'wlopez93,123456', 'athompson48,mustang', 'slewis57,WELCOME', 'dsanchez64,letmein', 'mhill65,Welcome', 'rtorres2,SHADOW', 'tclark98,SUNSHINE', 'jmiller70,QWERTY', 'mbaker3,123456', 'dmartin56,shadow', 'mhernandez54,Soccer', 'bbrown24,123456', 'twilson17,TrustNo1', 'dwilliams95,Shadow', 'dclark72,BASEBALL', 'syoung19,monkey', 'ascott12,SHADOW', 'jflores30,password123', 'sjackson35,Password', 'ethompson67,iLoveYou', 'arivera51,12345678', 'psmith55,QWERTY', 'dmartin1,QWERTY', 'badams82,Welcome', 'ebaker63,PASSWORD123', 'gdavis57,master', 'rjones70,Password', 'jlopez51,12345678', 'nflores42,superman', 'enguyen55,TRUSTNO1', 'jmiller2,Welcome', 'enelson31,123456', 'bmiller30,TrustNo1', 'sking33,MASTER', 'drobinson6,qwerty', 'droberts6,Welcome', 'eharris33,Dragon', 'rthompson52,soccer', 'dnelson68,letmein', 'psanchez40,LetMeIn', 'cadams96,Password123', 'rperez92,NINJA', 'aallen57,QWERTY', 'bbaker96,QWERTY', 'ssanchez23,111111', 'jdavis30,password', 'rtaylor34,ninja', 'khill90,HELLO', 'bnelson13,123456', 'sthomas62,Welcome', 'jcarter66,Admin', 'smartinez38,buster', 'tmoore35,iloveyou', 'gsanchez13,password123', 'nyoung5,Monkey', 'jsmith7,Shadow', 'kcarter51,Password', 'mwalker63,admin', 'kwright52,qwerty', 'wharris69,Football', 'grobinson17,Password', 'dmoore22,password', 'jrivera6,iloveyou', 'canderson64,Baseball', 'lclark87,password', 'nscott26,password123', 'jmiller38,sunshine', 'canderson12,QWERTY', 'gsanchez36,BASEBALL', 'staylor17,123456', 'srobinson60,123456', 'jadams93,Password123', 'aroberts93,password123', 'ryoung84,WELCOME', 'rroberts87,hunter', 'mnguyen49,QWERTY', 'dmiller1,qwerty', 'clewis28,abc123', 'gtorres38,Ginger', 'jtaylor40,sunshine', 'bgarcia51,thunder', 'glopez39,WELCOME', 'lscott33,ranger', 'mmoore97,Welcome', 'ecarter63,Admin', 'ddavis88,111111', 'lmoore89,DRAGON', 'jbaker39,PASSWORD123', 'rhall69,ILoveYou', 'kjohnson4,letmein', 'dbrown63,TRUSTNO1', 'jmitchell38,MONKEY', 'ljones14,123456', 'jmitchell14,Password123', 'jrobinson36,Admin', 'manderson65,12345678', 'dnelson61,SUNSHINE', 'jyoung97,Password123', 'kwright33,mustang', 'rdavis72,admin', 'mthomas38,abc123', 'banderson70,password123', 'ecampbell79,FOOTBALL', 'twhite54,LetMeIn', 'dhall74,Dragon', 'mmartin78,LetMeIn', 'wrodriguez89,Shadow', 'drivera13,mustang', 'grivera55,shadow', 'bflores86,ninja', 'sjackson55,shadow', 'ahall35,letmein', 'dlee58,DRAGON', 'aflores80,ginger', 'trobinson3,Password123', 'tjohnson77,Shadow', 'dgonzalez17,123456', 'ksmith59,qwerty', 'smartin70,ninja', 'ahall44,shadow', 'aadams95,starwars', 'mcampbell58,LetMeIn', 'jbaker64,123456', 'jwilliams70,Password123', 'dwright62,Hunter', 'mjackson21,MUSTANG', 'mhernandez19,princess', 'mgarcia34,password123', 'wlee33,Buster', 'sjackson33,welcome', 'shill33,letmein', 'dcampbell58,monkey', 'syoung21,123456', 'mjones75,abc123', 'jwilliams65,trustno1', 'dbaker40,sunshine', 'jtaylor29,Thunder', 'dadams41,BATMAN', 'pgreen22,111111', 'snelson46,ILoveYou', 'bmartinez28,123456', 'cramirez72,123456', 'ascott86,LETMEIN', 'ljones90,qwerty', 'escott43,Ginger', 'jscott51,letmein', 'sking69,dragon', 'nclark64,iloveyou', 'rjohnson69,Dragon', 'amartin32,Sunshine', 'jwilliams32,password123', 'gmitchell66,ILOVEYOU', 'mrodriguez19,PassWord123', 'athompson8,shadow', 'pking74,iloveyou', 'rjohnson61,12345678', 'phernandez41,ABC123', 'ljohnson66,Superman', 'gcampbell71,batman', 'cdavis85,hello', 'lbaker85,Hello', 'rclark9,Hunter', 'jlee95,qwerty', 'alopez81,111111', 'rsanchez45,password123', 'bdavis90,iLoveYou', 'jallen23,iLoveYou', 'swilson52,123456', 'gperez5,trustno1', 'sdavis84,123456', 'jnelson14,mustang', 'dhill15,Baseball', 'jthomas26,Superman', 'sthompson14,Admin', 'rwright13,qwerty', 'msmith3,12345678', 'wwhite17,LetMeIn', 'lcampbell23,123456', 'bdavis79,qwerty', 'jbaker19,Mustang', 'jwright59,Password123', 'ntaylor22,Qwerty', 'dlee34,QWERTY', 'pthomas53,letmein', 'sjackson77,Dragon', 'smartinez60,admin', 'lwilliams98,123456', 'amiller37,Password123', 'lsanchez8,123456', 'jwhite69,sunshine', 'jlee27,12345678', 'troberts88,Football', 'sallen31,Baseball', 'sanderson51,shadow', 'droberts2,123456', 'gflores16,Dragon', 'mwhite42,QWERTY', 'elopez35,123456', 'pwilson58,qwerty', 'jcarter31,Football', 'rwilson59,monkey', 'jlee84,password', 'ascott36,diamond', 'jgarcia55,ILOVEYOU', 'egreen16,12345678', 'mnguyen10,iLoveYou', 'kmartin88,QWERTY', 'kallen51,Password', 'pmartin57,LetMeIn', 'jjackson72,12345678', 'rtaylor87,PRINCESS', 'gjones78,FOOTBALL', 'djackson61,Letmein', 'scampbell84,hunter', 'ethompson20,abc123', 'jwhite41,dragon', 'sbaker36,Admin', 'eking16,monkey', 'wthomas24,MASTER', 'jmiller10,abc123', 'bsanchez86,qwerty', 'sharris99,Baseball', 'mrobinson84,Qwerty', 'mclark45,admin', 'jnelson45,WELCOME', 'jperez52,letmein', 'bscott70,123456', 'jlewis99,TrustNo1', 'jbaker15,MONKEY', 'rjohnson64,Master', 'jhall84,password', 'amitchell17,QWERTY', 'sking44,admin', 'bmitchell63,LetMeIn', 'ewhite13,LETMEIN', 'sanderson58,qwerty', 'rsanchez79,hunter', 'nhill88,123456', 'eanderson90,welcome', 'jrivera67,qwerty', 'dgonzalez83,PASSWORD123', 'kjones68,LETMEIN', 'mmartinez83,Monkey', 'jjackson12,starwars', 'gthompson30,Password123', 'cwhite64,admin', 'mking76,qwerty', 'mtorres8,123456', 'madams74,welcome', 'lwilliams85,iLoveYou', 'gmartin74,111111', 'mjackson80,sunshine', 'aclark78,Abc123', 'randerson32,PASSWORD', 'smoore89,LETMEIN', 'cjackson29,Password123', 'wtorres41,superman', 'kallen50,admin', 'jdavis37,Sunshine', 'dperez55,ranger', 'jhernandez51,ABC123', 'rmitchell19,Baseball', 'mrobinson21,baseball', 'eperez4,StarWars', 'syoung22,DRAGON', 'gcampbell77,DRAGON', 'dbaker43,letmein', 'psanchez61,Password', 'pnelson50,WELCOME', 'acarter28,123456', 'jwright42,baseball', 'ayoung74,111111', 'tperez31,iloveyou', 'mbrown30,shadow', 'ajones17,abc123', 'ascott63,password123', 'mclark64,HELLO', 'wclark62,111111', 'etorres23,StarWars', 'bwalker61,ninja', 'sthomas5,Princess', 'sanderson36,Hello', 'jwilliams25,admin', 'anelson67,Password', 'esanchez9,Thunder', 'twalker71,Qwerty', 'dwhite93,password123', 'rmiller81,monkey', 'agreen84,123456', 'wanderson85,PASSWORD', 'jwhite17,TRUSTNO1', 'ahernandez96,Password123', 'sclark53,qwerty', 'cthomas8,ninja', 'kflores71,Dragon', 'sscott67,123456', 'gmiller56,Football', 'blopez3,PassWord123', 'dmartinez17,111111', 'cbaker96,Welcome', 'pyoung96,Ninja', 'myoung6,Password123', 'mscott75,master', 'tgreen21,Soccer', 'clopez47,Hello', 'eflores12,Password123', 'bmitchell81,Password', 'dhill84,QWERTY', 'dsmith10,Soccer', 'pwalker26,123456', 'thernandez29,123456', 'amarti

In [ ]:
import pandas as pd
df = pd.read_csv("passwords.txt", header = None)
df. columns = ["username", "passwords"]
df

      username    passwords
0      bhall33  PASSWORD123
1    dcarter44        Admin
2    jrivera47       123456
3      khall11       qwerty
4    jmiller64     football
..         ...          ...
995   mbrown83       123456
996    eclark2       111111
997  sharris54  Password123
998  sthomas50       qwerty
999   rcarter9      letmein

[1000 rows x 2 columns]

In [ ]:
#Step 2.
total_passwords = len(df)
total_passwords
passwordCount = df["passwords"].value_counts()
passwordCount
passwordMostCount = passwordCount.iloc[0]
passwordMostCount
mostPasswordValue = passwordCount[passwordCount == passwordMostCount]
mostPasswordValue

passwords
123456    95
Name: count, dtype: int64

In [ ]:
#Step 3
df["password_lower"] = df["passwords"].str.lower()
passwordCount = df["password_lower"].value_counts()
passwordCount
mostCommonIndex = passwordCount.iloc[0]
mostCommonIndex
mostCommonPassword = passwordCount[passwordCount == mostCommonIndex]
mostCommonPassword

password_lower
password123    110
Name: count, dtype: int64

In [ ]:
#Step 4.
df["password_length"] = df["passwords"].str.len()
shortestPassword = df["password_length"].idxmin()
shortestPassword
shortestPasswordValue = df.loc[shortestPassword, "passwords"]
shortestPasswordValue
shortestlength = df.loc[shortestPassword, "password_length"]
shortestlength
print(shortestPasswordValue, shortestlength)

Admin 5

In [ ]:
#Step 5.
longestPassword = df["password_length"].idxmax()
longestPassword
longestPasswordValue = df.loc[longestPassword, "passwords"]
longestPasswordValue
longestlength = df.loc[longestPassword, "password_length"]
longestlength
print(longestPasswordValue,longestlength)

PASSWORD123 11

In [ ]:
#Step 6
letterString = df["passwords"].str.cat()
type(letterString)
letterSeries = pd.Series(list(letterString))
letterSeries
letterCounts = letterSeries[letterSeries.str.isalpha()].value_counts()
letterCounts
mostOccurringLetter = letterCounts.index[0]
mostOccurringLetter
print(mostOccurringLetter, letterSeries[letterSeries == mostOccurringLetter].count())

s 437

In [ ]:
#Step 7.
letterString = df["passwords"].str.cat()
type(letterString)
letterSeries = pd.Series(list(letterString))
letterSeries
letterCounts = letterSeries[letterSeries.str.isalpha()].value_counts()
letterCounts
leastOccurringLetter = letterCounts.index[-1]
leastOccurringLetter
leastCount=letterCounts.iloc[-1]
leastCount
print(leastOccurringLetter, leastCount)

x 1

In [ ]:
#Step 8.
df["has_uppercase"] = df["passwords"].str.contains(r"[A-Z]",regex=True)
df
UpperCaseDF = df[df["has_uppercase"]]

if len(UpperCaseDF) > 0:
  print(UpperCaseDF["passwords"].head(20).to_string(index=False))
  if len(UpperCaseDF) > 20:
    print(f" ... and {len(UpperCaseDF) - 20} more")
else:
    print("None Found.")
print(f" Total: {len(UpperCaseDF)}")
print()

PASSWORD123
      Admin
     Master
    LETMEIN
     ABC123
     SHADOW
     Monkey
    Mustang
Password123
    LETMEIN
     Qwerty
    Mustang
     Batman
     Merlin
    LetMeIn
     Qwerty
   Football
    ZXCVBNM
Password123
     Qwerty
 ... and 476 more
 Total: 496

In [ ]:
#Step 9.
df["lowerCase_noNum"] = df["passwords"].str.contains(r"^[a-z]+$", regex=True)
lowercaseDF = df[df["lowerCase_noNum"]]
lowercaseDF
if len(lowercaseDF) > 0:
    print(lowercaseDF["passwords"].head(20).to_string(index=False))
    if len(lowercaseDF) > 20:
        print(f" ... and {len(lowercaseDF) - 20} more")
else:
    print(" None Found.")
print(f" Total: {len(lowercaseDF)}")
print()

  qwerty
football
password
baseball
 letmein
   admin
  master
  qwerty
   ninja
iloveyou
  monkey
 letmein
princess
  hunter
iloveyou
   admin
sunshine
   hello
 letmein
  qwerty
 ... and 278 more
 Total: 298

In [ ]:
#Step 10
print(f"Passwords Analyzed: {total_passwords}")
print(f"Most Commmon Password: \n{mostCommonPassword}")
print(f"Longest Password and Length: {longestPasswordValue}, {longestlength}")
print(f"Uppercase Passwords: {len(UpperCaseDF)}")
print(f"Lowercase Passwords: {len(lowercaseDF)}")

Passwords Analyzed: 1000
Most Commmon Password:
password_lower
password123    110
Name: count, dtype: int64
Longest Password and Length: PASSWORD123, 11
Uppercase Passwords: 496
Lowercase Passwords: 298